name: "Reusable Terraform Deploy"

on:
  workflow_call:
    inputs:
      directory:
        description: 'Caminho completo do diretório Terraform (ex: terraform-infrastructure/asm-site/dev)'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: "AWS Access Key ID"
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: "AWS Secret Access Key"
        required: true
      AWS_DEFAULT_REGION:
        description: "AWS Default Region"
        required: true

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.directory }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_LOG: DEBUG
      TF_LOG_PATH: /tmp/terraform.log

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Display Terraform Log
        if: always()
        run: cat /tmp/terraform.log
